spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password:

  h2:
    console:
      enabled: true
      path: /test_db

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

#  logging:
#    level:
#      org.hibernate.type: trace

  thymeleaf:
    prefix: classpath:templates/
    check-template-location: true
    suffix: .html
    mode: HTML5
    cache: false
    order: 0